remote_theme: rundocs/jekyll-rtd-theme
scss: |
  @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+JP&family=Noto+Serif+JP:wght@400;500;700&display=swap');
  .text-uppercase{
    text-transform: none !important; 
  }
  .markdown-body{
    font-family: 'Noto Serif JP', serif; !important;
  }
  .h1 .h2 .h3 .h4 .h5{
    font-family: 'Noto Sans JP', sans-serif; !important;
  }
readme_index:
  with_frontmatter: true